apiVersion: apps/v1
kind: Deployment
metadata:
  name: jon-gb-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: jon-gb-ui
  template:
    metadata:
      labels:
        app: jon-gb-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: jon-gb-ui
        ports:
        - containerPort: 80
